# fly.toml app configuration file generated for quiet-silence-9827 on 2023-08-19T11:08:48+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quiet-silence-9827"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
